# Generated by Django 3.0.6 on 2020-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('problemId', models.IntegerField()),
                ('language', models.CharField(choices=[('CP', 'CPP'), ('JV', 'JAVA'), ('P3', 'PYTHON 3'), ('P2', 'PYTHON 2'), ('JS', 'JAVASCRIPT')], max_length=2)),
                ('code', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Q', 'QUEUED'), ('R', 'RUNNING'), ('AC', 'ACCEPTED'), ('CE', 'COMPILATION ERROR'), ('WA', 'WRONG ANSWER'), ('RE', 'RUNTIME ERROR')], max_length=2)),
                ('error', models.TextField(blank=True)),
                ('inputGiven', models.TextField(blank=True)),
                ('outputGen', models.TextField(blank=True)),
            ],
        ),
    ]
